(define (frame-coord-map frame) 
  (lambda (v)
    (add-vect
      (origin-frame frame)
      (add-vect (scale-vect (xcor-vect v) (edge1-frame frame))
                (scale-vect (ycor-vect v) (edge2-frame frame))))))

(define (segments->painter segment-list) 
  (lambda (frame)
    (for-each
      (lambda (segment)
        (draw-line 
          ((frame-coord-map frame)
           (start-segment segment)) 
          ((frame-coord-map frame)
           (end-segment segment)))) 
      segment-list)))

; a
(define (draw-frame)
  (let ((tl (make-vect 0 1))
        (tr (make-vect 1 1))
        (br (make-vect 1 0))
        (bl (make-vect 0 0)))
    (segments->painter (list (make-segment bl tl)
                             (make-segment tl tr)
                             (make-segment tr br)
                             (make-segment br bl)))))
; b
(define (diagonals)
  (let ((tl (make-vect 0 1))
        (tr (make-vect 1 1))
        (br (make-vect 1 0))
        (bl (make-vect 0 0)))
    (segments->painter (list (make-segment bl tr)
                             (make-segment br tl)))))
; c
(define (diamond)
  (let ((b (make-vect 0 0.5))
        (r (make-vect 1 0.5))
        (t (make-vect 0.5 1))
        (l (make-vect 0 0.5)))
    (segments->painter (list (make-segment b l)
                             (make-segment l t)
                             (make-segment t r)
                             (make-segment r b)))))
; d
(define (wave)
  (define (coords->segs coords)
    (if (null? (cdr coords))
      '()
      (cons (make-segment (car coords) (cadr coords))
            (coords->segs (cdr coords)))))
  (let ((list-of-coords (list (list (make-vect 0.45 1.0)
                                    (make-vect 0.4 0.875)
                                    (make-vect 0.45 0.775)
                                    (make-vect 0.45 0.75)
                                    (make-vect 0.35 0.75)
                                    (make-vect 0.2 0.6)
                                    (make-vect 0.0 0.775))
                              (list (make-vect 0.55 1.0)
                                    (make-vect 0.6 0.875)
                                    (make-vect 0.55 0.775)
                                    (make-vect 0.55 0.75)
                                    (make-vect 0.65 0.75)
                                    (make-vect 1.0 0.4))
                              (list (make-vect 0.0 0.7)
                                    (make-vect 0.2 0.5)
                                    (make-vect 0.4 0.65)
                                    (make-vect 0.4 0.4)
                                    (make-vect 0.3 0.0))
                              (list (make-vect 1.0 0.35)
                                    (make-vect 0.6 0.65)
                                    (make-vect 0.6 0.4)
                                    (make-vect 0.7 0.0))
                              (list (make-vect 0.4 0.0)
                                    (make-vect 0.5 0.35)
                                    (make-vect 0.6 0.0))
                                )))
    (segments->painter (accumulate append 
                                   '() 
                                   (map coords->segs list-of-coords)))))
